# Generated automatically from Makefile.in by configure.
SUBDIRS=src

build:
	@for x in $(SUBDIRS); do (cd $$x && $(MAKE) ); done

clean:
	@for x in $(SUBDIRS); do (cd $$x && $(MAKE) clean ); done

install:
	@for x in $(SUBDIRS); do (cd $$x && $(MAKE) install ); done	
	
romfs:
	$(ROMFSINST)  src/dnrd /bin/dnrd

