/* MiniUPnP Project
 * http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
 * (c) 2006 Thomas Bernard
 * generated by ./genconfig.sh on Mon Jul  2 10:55:35 CST 2007 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define UPNP_VERSION	"20070228"
#define OS_NAME		"Linux"
#define OS_VERSION	"Linux/2.4.22-1.2115.nptl"
#define OS_URL		"http://www.kernel.org/"

#define LOG_MINIUPNPD		 LOG_DAEMON

#endif
