/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux sbu-ii-1-server 2.6.24-19-generic #1 SMP Fri Jul 11 23:41:49 UTC 2008 i686 GNU/Linux"
#define BUILD_ENV_DATE "Wed May 11 11:44:35 CST 2011"
#define BUILD_ENV_SRCDIR "/home/fredfu/projects/WAG320N_v1_00_12_GPL/tk_apps/samba-3.0.22/source"
#define BUILD_ENV_BUILDDIR "/home/fredfu/projects/WAG320N_v1_00_12_GPL/tk_apps/samba-3.0.22/source"
#define BUILD_ENV_USER "fredfu"
#define BUILD_ENV_HOST "sbu-ii-1-server"
#define BUILD_ENV_COMPILER "/opt/toolchains/uclibc-crosstools/bin/mips-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
