# $Id: Makefile,v 1.1.1.1 2009-01-05 09:00:33 fred_fu Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
